/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package servlet.war.demo;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/hello")
public class Library extends HttpServlet {
    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String name;
        String age;
        String forward;
        if ((name = req.getHeader("name")) != null)
            resp.getWriter().println("Welcome, " + name);
        else if ((age = req.getParameter("age")) != null)
            resp.getWriter().println("Wow, you're " + age + " years old?");
        else if ((forward = req.getParameter("forward")).equals("forward"))
            req.getRequestDispatcher("main.js").forward(req, resp);
        else if ((forward = req.getParameter("forward")).equals("redirect"))
            resp.sendRedirect("log.txt");
        else {
            resp.setContentType("application/json");
            resp.getWriter().println("{'message':'Hello, there!'}");
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        doGet(req, resp);
    }
}
